name: Test Bob Action

on: [push, workflow_dispatch]

jobs:
  test-latest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest] # 'macos-13' is Intel, 'macos-latest' is M1.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap Bob (version=latest)
        id: bob
        uses: ./
        with:
          version: latest

      - name: Verify installed version
        run: echo "Installed Bob version is ${{ steps.bob.outputs.bob-version }}."

  test-specific:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Bootstrap Bob (version=v0.2.19)
        id: bob
        uses: ./
        with:
          version: v0.2.19

      - name: Verify installed version
        run: |
          echo "Installed Bob version is ${{ steps.bob.outputs.bob-version }}."
          test "${{ steps.bob.outputs.bob-version }}" = "v0.2.19"
